---

- name: Download fleet archive
  get_url:
    url: "{{ kolide_fleet_url }}"
    dest: "/var/tmp/fleet.zip"
    mode: '0644'
    checksum: "{{ kolide_fleet_hash }}"

- name: Unarchive fleet
  unarchive:
    src: "/var/tmp/fleet.zip"
    dest: /var/tmp
    creates: /var/tmp/linux/fleet

- name: Install fleet binaries
  copy:
    src: "{{ item.s }}"
    dest: "{{ item.d }}"
    mode: '0755'
    owner: root
    remote_src: true
  with_items:
    - { s: /var/tmp/linux/fleet_linux_amd64, d: /usr/bin/fleet }

