---

- name: Create Azure MySQL Server
  azure_rm_mysqlserver:
    resource_group: "{{ kolide_mysqlazure_rg }}"
    name: "{{ kolide_mysqlazure_name }}"
    sku:
      name: B_Gen5_1
      tier: Basic
    version: 5.7
    enforce_ssl: True
    admin_username: "{{ kolide_mysql_root_user | default('mysqlroot_kolide') }}"
    admin_password: "{{ kolide_mysql_root_pass }}"
    storage_mb: 51200
  delegate_to: localhost
  become: no

- name: Create instance of Azure MySQL Database
  azure_rm_mysqldatabase:
    resource_group: "{{ kolide_mysqlazure_rg }}"
    server_name: "{{ kolide_mysqlazure_name }}"
    name: "{{ kolide_mysql_db }}"
  delegate_to: localhost
  become: no

- name: Query Azure MySQL Servers in current resource group
  azure_rm_mysqlserver_info:
    resource_group: "{{ kolide_mysqlazure_rg }}"
  register: mysqlserverfacts
  delegate_to: localhost
  become: no

- name: Dump Azure MySQL Server facts
  debug:
    var: mysqlserverfacts

- name: Set fact kolide_mysql_host
  set_fact:
    kolide_mysql_host: "{{ mysqlserverfacts['servers'][0]['fully_qualified_domain_name'] }}"

# FIXME! executes without error but
#       warning 'Azure API profile latest does not define an entry for MySQLManagementClient'
#       firewall access not effective in later configuration
- name: Open firewall to access MySQL Server from allowed source IPs - <2.8
  azure_rm_resource:
    api_version: '2017-12-01'
    resource_group: "{{ kolide_mysqlazure_rg }}"
    resource_name: "{{ kolide_mysqlazure_name }}"
    provider: dbformysql
    resource_type: servers
    subresource:
      - type: firewallrules
        name: externalaccess
    body:
      properties:
        startIpAddress: "{{ item }}"
        endIpAddress: "{{ item }}"
  with_items: "{{ kolide_mysqlazure_allowed_srcip }}"
  delegate_to: localhost
  become: no
  when: "ansible_version.full is version_compare('2.8', '<')"

- name: Open firewall to access MySQL Server from allowed source IPs - >=2.8
  azure_rm_mysqlfirewallrule:
    resource_group: "{{ kolide_mysqlazure_rg }}"
    server_name: "{{ kolide_mysqlazure_name }}"
    name: "firewallrule-allow-src-{{ item }}"
    start_ip_address: "{{ item }}"
    end_ip_address: "{{ item }}"
  with_items: "{{ kolide_mysqlazure_allowed_srcip }}"
  delegate_to: localhost
  become: no
  when: "ansible_version.full is version_compare('2.8', '>=')"
