---
name: AnsibleCI

on:
  push:
  pull_request:
  schedule:  # run weekly, every Tuesday 03:00
    - cron: '0 3 * * 2'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
    env:
      ANSIBLE_CALLBACK_WHITELIST: profile_tasks
      ANSIBLE_EXTRA_VARS: ""

    steps:
      - uses: actions/checkout@v2
        with:
          path: juju4.kolide
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install ansible-lint flake8 yamllint
          ansible --version
          cd $GITHUB_WORKSPACE/juju4.kolide
          [ -f get-dependencies.sh ] && sh -x get-dependencies.sh
          { echo '[defaults]'; echo 'callback_whitelist = profile_tasks, timer'; echo 'roles_path = ../'; echo 'ansible_python_interpreter: /usr/bin/python3'; } >> ansible.cfg
      - name: yamllint
        run: |
          pwd
          find -ls
          cd $GITHUB_WORKSPACE/juju4.kolide && yamllint .
      - name: ansible-lint
        run: |
          cd $GITHUB_WORKSPACE/juju4.kolide && ansible-lint
      - name: run test
        run: |
          cd $GITHUB_WORKSPACE/juju4.kolide && ansible-playbook -i localhost, --connection=local --become -vvv test/integration/default/default.yml ${ANSIBLE_EXTRA_VARS}
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
      - name: idempotency run
        run: |
          cd $GITHUB_WORKSPACE/juju4.kolide && ansible-playbook -i localhost, --connection=local --become -vvv test/integration/default/default.yml ${ANSIBLE_EXTRA_VARS} | tee /tmp/idempotency.log | grep -q 'changed=0.*failed=0'  && (echo 'Idempotence test: pass' && exit 0)  || (echo 'Idempotence test: fail' && cat /tmp/idempotency.log && exit 0)
      - name: On failure
        run: |
          ansible -i inventory --connection=local -m setup localhost
          systemctl -l --no-pager status
          systemctl -l --no-pager --failed
          ls -l /usr/bin/ | egrep '(python|pip|ansible)'
          pip freeze
          pip3 freeze
          ip addr
          cat /etc/resolv.conf
          host www.google.com
          ping -c 1 www.google.com
          ping -c 1 8.8.8.8
        if: ${{ failure() }}
      - name: After script - systemd
        run: |
          systemctl -l --no-pager status kolide || true
          systemd-analyze security || true
          rsyslogd -v
        continue-on-error: true
      - name: After script - setup
        run: |
          mysql -u kolide --password=Kolide!2017@ -Be \"select * from app_configs;\" kolidedb'
          fleetctl get options
          fleetctl get enroll-secret
        continue-on-error: true
      - name: After script - curl
        run: |
          curl -vk https://localhost:8080/healthz
          curl -vk https://localhost:8080/hosts
          curl -vk https://localhost:8080/hosts/manage
          curl -vk https://localhost:8080/api/v1/kolide/packs
          curl -vk https://localhost:8080/api/v1/kolide/hosts
          curl -vk -X POST https://localhost:8080/api/v1/osquery/enroll
        continue-on-error: true
      - name: After script - etc
        run: |
          cat /etc/kolide/kolide.yml
        continue-on-error: true
      - name: After script - files
        run: |
          cat /root/.fleet/config
          ls /var/log/kolide/
          ls /var/log/ /var/log/mysql/
          cat /var/log/mysqld.log
          cat /var/log/mysql/mysqld.log        continue-on-error: true
